# standard jekyll configuration

safe:           true
lsi:            false
permalink:      /post/:title
pygments:       true
markdown:       rdiscount
markdown_ext:   markdown,mkd,mkdn,md
textile_ext:    textile

# enables SmartyPants (nice curly quotation marks, em/en dashes, elipses, etc):
rdiscount:
    extensions: [smart]

# configuration required for some pages

domain:         haixing-hu.github.io
name:           Haixing Hu's Home Page
author:         Haixing Hu
email:          starfish.hu@gmail.com

license:
  url:        http://creativecommons.org/licenses/by-nc-sa/3.0/
  img:        [/img/cc.png, /img/by.png, /img/nc.png, /img/sa.png]

# since the `categoreis` is predefined collection of `site`, we have to use
# another name for the following property
sections: 
  - {name: home, url: /index.html, banner: }
  - {name: study, url: /study.html, banner: /img/banner_study.jpg}
  - {name: work, url: /work.html, banner: /img/banner_work.jpg}
  - {name: life, url: /life.html, banner: /img/banner_life.jpg}
  - {name: about, url: /about.html, banner: /img/banner_about.jpg}

# configuration for enhancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
  username:   Haixing-Hu
  repository: Haixing-Hu.github.io
